# Generated by Django 3.2.7 on 2021-10-01 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('idConsulta', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('dia', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('estado', models.CharField(default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('idMensaje', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.CharField(max_length=500)),
                ('hora', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('usuario', models.CharField(max_length=10)),
                ('estado', models.CharField(default='A', max_length=1)),
                ('idConsulta', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=120)),
                ('correo', models.EmailField(max_length=200)),
            ],
        ),
    ]
